using CincoVertice.Common.Application.CodeStandard.Fixers;
using Xunit;

namespace CincoVertice.Common.Application.Tests.CodeStandard.Fixers;

public class TrailingOperatorFixerTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void Fix_WhenContentIsNullOrEmpty_ReturnsEmpty(string? content)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content!);

        // Assert
        Assert.Equal(string.Empty, result);
    }

    [Theory]
    [InlineData("if (a &&\r\n    b)", "if (a\r\n    && b)")]
    [InlineData("if (a ||\r\n    b)", "if (a\r\n    || b)")]
    [InlineData("var x = a ??\r\n    b;", "var x = a\r\n    ?? b;")]
    [InlineData("x ??=\r\n    y;", "x\r\n    ??= y;")]
    [InlineData("var x = a +\r\n    b;", "var x = a\r\n    + b;")]
    [InlineData("var x = a *\r\n    b;", "var x = a\r\n    * b;")]
    [InlineData("var x = a /\r\n    b;", "var x = a\r\n    / b;")]
    public void Fix_MovesTrailingOperatorToStartOfNextLine(string content, string expected)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(expected, result);
    }

    [Fact]
    public void Fix_MovesTernaryOperatorsAcrossLines()
    {
        // Arrange
        string content =
            "var x = cond ?\r\n"
            + "    a :\r\n"
            + "    b;";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(
            "var x = cond\r\n"
            + "    ? a\r\n"
            + "    : b;",
            result);
    }

    [Fact]
    public void Fix_KeepsExistingIndentationWithoutAddingMore()
    {
        // Arrange - the continuation is already indented; the operator goes at that same indent.
        string content = "        return a &&\r\n        b;";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal("        return a\r\n        && b;", result);
    }

    [Fact]
    public void Fix_CascadesMultipleTrailingOperators()
    {
        // Arrange
        string content =
            "var x = a +\r\n"
            + "b +\r\n"
            + "c;";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(
            "var x = a\r\n"
            + "+ b\r\n"
            + "+ c;",
            result);
    }

    [Theory]
    [InlineData("case 1:\r\n    DoStuff();")]
    [InlineData("default:\r\n    Break();")]
    public void Fix_DoesNotMoveColonOnSwitchLabels(string content)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_MovesColonForBaseConstructorInitializer()
    {
        // Arrange
        string content = "public Foo() :\r\n    base()";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal("public Foo()\r\n    : base()", result);
    }

    [Theory]
    [InlineData("x +=\r\n    y;")]   // compound assignment ends with '=', not an operator in scope
    [InlineData("if (a ==\r\n    b)")]
    [InlineData("var f = () =>\r\n    x;")]
    public void Fix_DoesNotMoveOperatorsOutOfScope(string content)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_DoesNotMoveOperatorsInXmlDocComments()
    {
        // Arrange
        string content =
            "///     Handles both <c>CallbackSent</c> and <c>CertificateRequested</c> states:\r\n"
            + "///     processes the certificate and advances to <c>Completed</c> or <c>CertificateFailed</c>.";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_DoesNotModifyTrailingSlashInXmlDocComment()
    {
        // Arrange
        string content =
            "    /// <summary>\r\n"
            + "    ///     Gets or sets the condition key. Used by <c>PayloadProperty*</c> rules to identify the\r\n"
            + "    ///     request body property name (e.g. <c>quoteId</c>), and by <c>HeaderValue</c>/\r\n"
            + "    ///     <c>HeaderAndPath</c> rules to identify the header name (e.g. <c>X-Nu-Product-Type</c>).\r\n"
            + "    /// </summary>";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_DoesNotModifyTrailingDashInAutoGeneratedHeaderComment()
    {
        // Arrange
        string content =
            "//-----------------------------------------------------------------------------\r\n"
            + "// <auto-generated>";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Theory]
    [InlineData("// sum a +\r\nnext")]
    [InlineData("    // ternary cond ?\r\n    next")]
    public void Fix_DoesNotMoveOperatorsInComments(string content)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_DoesNotMoveOperatorsInsideBlockComment()
    {
        // Arrange
        string content =
            "/*\r\n"
            + " * a plus b +\r\n"
            + " */";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_MovesChainedMultiplicationAcrossLines()
    {
        // Arrange
        string content =
            "        var expectedInputsCount = devicesDetails.Count *\r\n"
            + "            quoteRequest.Options.Count *\r\n"
            + "            firstOption.Offers.Count;";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(
            "        var expectedInputsCount = devicesDetails.Count\r\n"
            + "            * quoteRequest.Options.Count\r\n"
            + "            * firstOption.Offers.Count;",
            result);
    }

    [Fact]
    public void Fix_DoesNotMangleBlockCommentDelimiters()
    {
        // Arrange
        string content = "/*\r\n * doc\r\n */";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_WhenLastLineEndsWithOperator_LeavesItUnchanged()
    {
        // Arrange - nowhere to move it to.
        string content = "var x = a &&";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(content, result);
    }

    [Fact]
    public void Fix_PreservesLfLineEndings()
    {
        // Act
        var result = new TrailingOperatorFixer().Fix("if (a &&\n    b)");

        // Assert
        Assert.Equal("if (a\n    && b)", result);
    }

    [Fact]
    public void Fix_IsIdempotent()
    {
        // Arrange
        string content = "if (a &&\r\n    b)";

        // Act
        var once = new TrailingOperatorFixer().Fix(content);
        var twice = new TrailingOperatorFixer().Fix(once);

        // Assert
        Assert.Equal(once, twice);
    }

    [Fact]
    public void Fix_MovesMinusOperator()
    {
        // Act
        var result = new TrailingOperatorFixer().Fix("var x = a -\r\n    b;");

        // Assert
        Assert.Equal("var x = a\r\n    - b;", result);
    }

    [Theory]
    [InlineData("x ??=\r\n    y;", "x\r\n    ??= y;")]
    [InlineData("x ??\r\n    y;", "x\r\n    ?? y;")]
    [InlineData("x ?\r\n    y;", "x\r\n    ? y;")]
    public void Fix_MatchesLongestOperatorFirst(string content, string expected)
    {
        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(expected, result);
    }

    [Fact]
    public void Fix_WhenTrailingWhitespaceAfterOperator_StillMoves()
    {
        // Act
        var result = new TrailingOperatorFixer().Fix("if (a &&   \r\n    b)");

        // Assert
        Assert.Equal("if (a\r\n    && b)", result);
    }

    [Fact]
    public void Fix_WhenNoSpaceBeforeOperator_StillMoves()
    {
        // Act
        var result = new TrailingOperatorFixer().Fix("x = a+\r\n    b;");

        // Assert
        Assert.Equal("x = a\r\n    + b;", result);
    }

    [Fact]
    public void Fix_UsesTabIndentationOfContinuationLine()
    {
        // Act
        var result = new TrailingOperatorFixer().Fix("if (a &&\r\n\tb)");

        // Assert
        Assert.Equal("if (a\r\n\t&& b)", result);
    }

    [Fact]
    public void Fix_LeavesUnrelatedLinesUnchanged()
    {
        // Arrange
        string content =
            "public int Sum()\r\n"
            + "{\r\n"
            + "    return a +\r\n"
            + "        b;\r\n"
            + "}";

        // Act
        var result = new TrailingOperatorFixer().Fix(content);

        // Assert
        Assert.Equal(
            "public int Sum()\r\n"
            + "{\r\n"
            + "    return a\r\n"
            + "        + b;\r\n"
            + "}",
            result);
    }
}
