namespace CincoVertice.Common.WinApi.Libs.Structs;

/// <summary>
///     The information about a simulated hardware event.
/// </summary>
public struct HARDWAREINPUT
{
    /// <summary>The message generated by the input hardware.</summary>
    public uint UMsg;

    /// <summary>The low-order word of the lParam parameter for uMsg.</summary>
    public ushort WParamL;

    /// <summary>The high-order word of the lParam parameter for uMsg.</summary>
    public ushort WParamH;
}
